[[plugins]]
 repo = 'Shougo/dein.vim'

[[plugins]]
 repo = 'Shougo/vimproc.vim'

[[plugins]]
 repo =  'scrooloose/syntastic'

[[plugins]]
 repo = 'w0rp/ale'

[[plugins]]
 repo = 'vim-airline/vim-airline'

[[plugins]]
 repo = 'vim-airline/vim-airline-themes'
 
[[plugins]]
 repo = 'sheerun/vim-wombat-scheme'
 
[[plugins]]
 repo = 'ryanoasis/vim-devicons'
 
[[plugins]]
 repo = 'Shougo/deoplete.nvim'

[[plugins]]
 repo = 'roxma/nvim-yarp'

[[plugins]]
 repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
 repo = 'thinca/vim-quickrun'

[[plugins]]
 repo = 'tpope/vim-fugitive'
