[[plugins]]
 repo = 'Shougo/dein.vim'

[[plugins]]
 repo = 'Shougo/vimproc.vim'

[[plugins]]
 repo = 'vim-airline/vim-airline'

# A collection of themes for vim-airline
[[plugins]]
 repo = 'vim-airline/vim-airline-themes'
 
# Wombat-like scheme
[[plugins]]
 repo = 'sheerun/vim-wombat-scheme'
 
# Adds file type icons to Vim plugins
[[plugins]]
 repo = 'ryanoasis/vim-devicons'
 
# Runs any commands and show results of thoese in buffer
[[plugins]]
 repo = 'thinca/vim-quickrun'

# A Git wrapper
[[plugins]]
 repo = 'tpope/vim-fugitive'

# Load extensions like VSCode and host language servers
[[plugins]]
 repo = 'neoclide/coc.nvim'
 rev = 'release'
 merged = '0'
